import json
from app.workflows.state_management import AgentState
from app.services.llm_service import LLMService
from app.agents.business_analyst.agent import update_agent_status
from app.core.logging import agent_logger

def run_judge(state: AgentState) -> AgentState:
    version_id = state.get("version_id")
    agent_logger.info(f"Running Judge Agent to validate agent outputs...")
    update_agent_status(version_id, "Judge Agent", "RUNNING")

    system_instruction = (
        "You are a Principal Software Architect and Quality Assurance Judge.\n"
        "Your task is to review all technical plans generated by previous agents (Business Analyst, Product Manager, Solution Architect, Database Architect, API Designer, Security Agent).\n"
        "Verify:\n"
        "1. Completeness: Are all required components present?\n"
        "2. Consistency: Do the API definitions, database tables, and system architecture align perfectly?\n"
        "3. Realism: Are cost estimations and scalability plans realistic?\n\n"
        "Format your output strictly as a JSON object containing the keys:\n"
        "- 'approved': boolean (true if everything is consistent and valid, false if there are gaps or conflicts)\n"
        "- 'reasoning': string summary of your evaluation\n"
        "- 'feedbacks': list of objects with 'agent_name' (e.g. 'Database Architect') and 'feedback' (string details for correction) - only fill if approved is false.\n"
    )

    # Compile the outputs to review
    inputs_to_review = {
        "business_analysis": state.get("business_analysis", {}),
        "product_requirements": state.get("product_requirements", {}),
        "system_architecture": state.get("system_architecture", {}),
        "database_design": state.get("database_design", {}),
        "api_design": state.get("api_design", {}),
        "security_review": state.get("security_review", {})
    }

    try:
        result = LLMService.generate_structured(
            prompt=json.dumps(inputs_to_review),
            system_instruction=system_instruction
        )
        
        approved = result.get("approved", True)
        if not approved:
            state["retry_count"] = state.get("retry_count", 0) + 1

        state["judge_review"] = {
            "approved": approved,
            "reasoning": result.get("reasoning", ""),
            "feedbacks": result.get("feedbacks", [])
        }
        
        update_agent_status(version_id, "Judge Agent", "COMPLETED", output=str(result))
    except Exception as e:
        error_msg = f"Judge Agent failed: {str(e)}"
        agent_logger.error(error_msg)
        update_agent_status(version_id, "Judge Agent", "FAILED", error_message=error_msg)
        state["errors"].append(error_msg)
        # Fallback: approve to prevent infinite loops on model errors
        state["judge_review"] = {
            "approved": True,
            "reasoning": f"Fallback approval due to Judge model exception: {str(e)}",
            "feedbacks": []
        }
        
    return state
